# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='manors',
            new_name='majors',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='학번'),
        ),
    ]
