# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20170611_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='enterance_year',
            field=models.CharField(default='none', max_length=100, verbose_name='학번'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='튜터이름'),
        ),
    ]
